name: on_pull_request
on:
  pull_request:
    branches: [master]
jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Install Requirements
        run: |
          mkdir -p $HOME/bin
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b $HOME/bin
          echo "$HOME/bin" >> $GITHUB_PATH
          python3 -m pip install setuptools
          python3 -m pip install pylint
          python3 -m pip install netapp-ontap
      - uses: actions/checkout@v2
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd examples; python3 -m pylint python_client_library | reviewdog -reporter=github-pr-check -diff="git diff master" -efm="%f:%l:%c: %m"
